config/routes.rb
Slideshow::Application.routes.draw do

  resources :pictures

  get "pictures/index"
  get "pictures/new"

  root 'pictures#index'

  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  def index
    respond_to do |format|
      format.json {
        @pics = Picture.all
        render json: @pics
      }
      format.html
    end
  end

  def new
    @pic = Picture.new
  end

  def create
    @pic = Picture.new(picture_params)
    if @pic.save
      redirect_to :index
    else
      render :new
    end
  end

  private
    def picture_params
      params.require(:picture).permit(:image, :name, :caption)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def include_javascript(file)
    content_for :included_js do
      javascript_include_tag file
    end
  end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Slideshow</title>
  <%= stylesheet_link_tag "bootstrap.min", "bootstrap-responsive.min", media: "all" %>
  <%= javascript_include_tag "//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js","underscore","backbone", "bootstrap.min" %>
  <%= yield :included_js %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">Kristi and Chris' Wedding</a>
    </div>
  </div>
</div>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/pictures/index.html.erb
<%
  include_javascript 'pictures'
%>
<h1>Pictures#index</h1>
<p>Find me in app/views/pictures/index.html.erb</p>

app/views/pictures/new.html.erb
<%= form_for @pic, url: pictures_path, html: { multipart: true, class: 'form-horizontal' } do |f| %>
  <% if @pic.errors.any? %>
    <div class="alert alert-error">
      <% @pic.errors.full_messages.each do |msg| %>
        <p><%= msg %></p>
      <% end %>
    </div>
  <% end %>
  <fieldset>
    <legend>Add a Picture!</legend>
    <div class="control-group">
      <%= f.label :image, 'Select your file.', class: 'control-label' %>
      <div class="controls">
        <%= f.file_field :image %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :name, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :name %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :caption, class: 'control-label' %>
      <div class="controls">
        <%= f.text_field :caption %>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Add</button>
      </div>
    </div>
  </fieldset>
<% end %>